# Generated by Django 3.2.3 on 2021-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
